apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
#  clusterIP: 10.254.97.97
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30080
