apiVersion: v1
kind: Pod
metadata:
  name: nodeselector
  namespace: default
  labels: 
    app: myapp
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  nodeSelector:
    disk: sata
