apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-ds 
  namespace: default
spec:
  selector:
    matchLabels:
      app: filebeat
      release: stable
  template:
    metadata:
      labels:
        app: filebeat
        release: stable
    spec:
      containers:
      - name: filebeat
        image: ikubernetes/myapp:v1
