apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    szh.com/create-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html/
  - name: busybox
    image: busybox:latest
    imagePullPolicy:  IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    - "while true ;do echo $(date) >>/data/index.html;sleep 2;done"
    volumeMounts:
    - name: html
      mountPath: /data/
  volumes:
  - name: html
    emptyDir: {}
